name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write
  id-token: write

jobs:
  build-infra:
    name: "Build Infra"
    uses: ./.github/workflows/build.yml
    with:
      package: infra

  deploy-dev:
    name: "Deploy"
    needs:
      [build-infra]
    uses: ./.github/workflows/deploy.yml
    with:
      aws-account-number: "954976306395"
      environment: Dev
      working-directory: infra
      download-artifact: false
