name: Deploy CDK

on:
  workflow_call:
    inputs:
      aws-account-number:
        required: true
        type: string
      environment:
        required: true
        type: string
      working-directory:
        required: true
        type: string
      run-bootstrap-command:
        required: false
        default: true
        type: boolean
      download-artifact:
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@a3252b78c470e02df07e9d59298aceedc3ccd6d6 # v3.0.0
      with:
        version: 8.2.0
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install pnpm
      run: npm install -g pnpm    
    - name: pnpm install
      run: pnpm install --frozen-lockfile
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-number }}:role/oidc-access-role
        aws-region: us-east-1
    - name: CDK Bootstrap
      if: ${{ inputs.run-bootstrap-command }}
      run: pnpm exec cdk bootstrap aws://${{ inputs.aws-account-number }}/us-east-1
      env:
        BRANCH_REF: ${{ github.ref }}
    - run: pnpm run deploy "${{ inputs.environment }}/**" --require-approval never
      env:
        BRANCH_REF: ${{ github.head_ref || github.ref }}